const userNumber = document.getElementById("user-Input");
const oddEven = document.getElementById("Even-Odd");
const winOrLose = document.getElementById("win-or-lose");


const btn = document.getElementById("btn-submit");

btn.addEventListener("click", function () {
  const number = parseInt(userNumber.value);
  const pcNumber = randomOneToFive();
  const oddEvenValue = parseInt(oddEven.value);
  if (number < 1 || number > 5 || isNaN(number)) {
    alert("You need to choose a number between 1 and 5. Please choose again.")
  }

  // Print in console
  console.log("Here is the number you chose:")
  console.log(number);//Print of the number by the user
  console.log("Here is the number the pc generated:")
  console.log(pcNumber);//Print of the random number generated by the pc with the function rnadomOneToFive();
  console.log("Let's sum them!");
  console.log(number + pcNumber);//Print of the sum
  const sum = number + pcNumber;//const of the SUM;
  const result = oddOrEven(sum); // If the sum number is odd, it's 1. If it's even, it's 2. Check Function oddOrEven(x) below;

  //If the result is compatible or not with the choice you made (Odd or Even), you will rieceive one of the following:
  if (result === oddEvenValue) {
    console.log("You won!")
    document.getElementById("win-or-lose").innerHTML = "You Won!";
    winOrLose.classList.remove("text-danger");
    winOrLose.classList.add("text-success");
  } else {
    console.log("You lost...")
    document.getElementById("win-or-lose").innerHTML = "You lost...";
    winOrLose.classList.remove("text-success");
    winOrLose.classList.add("text-danger");
  }

  //Print in HTML
  document.getElementById("user-number-input").innerHTML = number;
  document.getElementById("pc-number-generated").innerHTML = pcNumber;
  document.getElementById("result").innerHTML = sum;
})


//Function to calculate the number from 1 to 5 for pc;
function randomOneToFive() {
  const random = Math.floor(Math.random() * 5) + 1;
  return random;
}

//Function to check if a number is an odd number or even number;
function oddOrEven(x) {
  if (x % 2 === 0) {
    const even = 2;
    return even;
  } else {
    const odd = 1;
    return odd;
  }
}